name: Branch Cleanup

on:
  schedule:
    # Run this action daily at 12:00 PM
    - cron: '0 12 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository containing the branches
      - uses: actions/checkout@v2.38.2
      # Get a list of all branches in the repository
      - run: git branch --all
      # Filter the list of branches to only include those that are older than 10 days
      - run: |
        git for-each-ref --format="%(refname)" refs/heads/ | while read branch; do
          date=$(git log -1 --format=%cd $branch)
          date_in_seconds=$(date -d "$date" +%s)
          ten_days_ago_in_seconds=$(date -d "-10 days" +%s)
          if [ "$date_in_seconds" -lt "$ten_days_ago_in_seconds" ]; then
            echo "$branch is older than 10 days"
          fi
        done
      # Send a notification to @asho311 with a link to delete each branch in question
      - name: Send notification
        uses: peter-evans/create-or-update-issue@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: YOUR_USERNAME_OR_ORGANIZATION_NAME
          repo: YOUR_REPO_NAME
          title: "Branch Cleanup"
          body: |
            Hi @asho311,
            There are branches that are older than 10 days and need to be deleted.
            Here is a list of branches and a link to delete each branch:
            $BRANCH_LIST
            Thanks!
          labels: branch-cleanup
