name: Delete abandoned branches

on:
  schedule:
    - cron: "5 * * * *"

jobs:
  delete_abandoned_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Delete abandoned branches
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v1.1.1
        with:
          days-old: 7
          branches: 'main-pre-merge/*'
          exclude-branches: 'main'
