name: List abandoned branches

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  list_abandoned_branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0
        with:
          fetch-depth: 0
      - name: List abandoned branches
        run: |
          # Get the current time
          NOW=$(date +%s)
          
          # Iterate over all branches
          for branch in $(git branch -r | grep -v HEAD); do
            # Get the time that the branch was last updated
            LAST_UPDATED=$(git log -1 --format=%at $branch)
          
            # Calculate the difference in minutes between now and the last update
            DIFF_MINUTES=$(((NOW - LAST_UPDATED) / 60))
          
            # If the difference is greater than 7 minutes, print the branch name
            if [ $DIFF_MINUTES -gt 7 ]; then
              echo $branch
            fi
          done