name: Delete old branches

# on:
#   schedule:
#     - cron: "*/5 * * * *" # Run every 5 minutes

on: [push]

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branches
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branches: main-pre-merge/*
          minutes-old: 7
          dry-run: true
