name: Delete old branches

# on:
#   schedule:
#     - cron: "*/5 * * * *" # Run every 5 minutes

on: [push]

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branches
        uses: actions/delete-branches@v3.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-pattern: 'main-pre-merge/.*'
          older-than: 7 minutes
          include-protected: false
