name: Pre-release
on:
  pull_request:
    types: [ opened ]
    branches:
      - develop

jobs:
  create_pre_release_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          ref: master
      - name: Create pre-release branch
        run: |
          CURRENT_DATE=$(date +'%d%b%Y_%H%M')
          git checkout -b pre-release/$CURRENT_DATE

  merge_develop_into_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          ref: master
      - name: Merge develop into master
        run: |
          git merge develop
