name: Pre-merge-to-main
on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  create_pre_release_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          ref: main
      - name: Create pre-merge branch
        run: |
          CURRENT_DATE=$(date +'%d%b%Y_%H%M')
          git checkout -b pre-merge/$CURRENT_DATE
          git push -u origin pre-merge/$CURRENT_DATE
